// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (l *Location) Users(ctx context.Context) (result []*User, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = l.NamedUsers(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = l.Edges.UsersOrErr()
	}
	if IsNotLoaded(err) {
		result, err = l.QueryUsers().All(ctx)
	}
	return result, err
}

func (u *User) Location(ctx context.Context) (*Location, error) {
	result, err := u.Edges.LocationOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryLocation().Only(ctx)
	}
	return result, err
}
